name: Latest Medium Posts
on:
  schedule:
    - cron: '0 * * * *'  # hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@GibranF"

