name: Latest Medium Posts

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:      # Allow manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Medium RSS and Update README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@gibranf"
